// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gldwxjskiduiqppicvyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsZHd4anNraWR1aXFwcGljdnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2OTEzNzksImV4cCI6MjA2NzI2NzM3OX0.HqQLKn6myKCwFhbPlAECLIdYM-P_7BcFXPHVEJJh1yQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});